### ISSUE TITLE
[bug] Mussel Draining Battery

### ISSUE THREAD

**Issue by pavel-tomka** [EntySec/SeaShell#8] opened 2024-01-12 06:09 UTC
The phone heats up to 40 degrees Celsius when using the payload. it also drains the battery very quickly even when it is not controlled

Iphone 11 - OS: iOS 16.2

![ABA27F72-BFB9-46E6-B9F7-1116CE891B3E](https://github.com/EntySec/SeaShell/assets/71507999/b5e14cd9-48d5-4e5e-bca1-28dc133ba6c6)

**Comment by enty8080** [comment] 2024-01-12 09:10
@pavel-tomka It's now about the payload, it's about something else. May I ask you how do you uninstall applications installed by TrollStore?

**Comment by enty8080** [comment] 2024-01-12 09:44
@pavel-tomka I found this one, might be related to your problem - https://otvet.mail.ru/question/192055414

**Comment by pavel-tomka** [comment] 2024-01-12 13:38
this is precisely because of this application. TrollStore applications are also displayed in the battery menu and are deleted in the same way. I installed the payload on my phone and after noticing it was getting very hot, I removed it. After that the phone did not warm up. if you want I can install the payload again and test it

**Comment by enty8080** [comment] 2024-01-12 13:51
@pavel-tomka Yes, please install it one more time. It can't be Mussel, since it has almost no impact on the system. However I'll check the payload one more time and test it on my device.

**Comment by enty8080** [comment] 2024-01-12 13:55
@pavel-tomka I confirmed that this is a bug and I will start working on a fix immediately.

**Comment by pavel-tomka** [comment] 2024-01-12 14:07
OK, thank you. should I close the issue?

**Comment by enty8080** [comment] 2024-01-12 14:10
@pavel-tomka I will close it when the bug is fixed.

**Comment by enty8080** [comment] 2024-01-12 15:12
UPD: Strange thing, I noticed CocoaTop shows that Mussel does not take a lot of system resources, so I don't know what's the cause of this issue. I know it's definitely not the application in self, because all it does is just print few words on a screen. The problem might be in [Pwny](https://GitHub.com/EntySec/Pwny) payload.

**Comment by pavel-tomka** [comment] 2024-01-12 17:11
first I opened the link, then I opened the application. after that I tried to access the camera. when I chose the camera there was a very long wait and then an error. I didn't do anything else
do you speak russian?

**Comment by enty8080** [comment] 2024-01-12 17:14
@pavel-tomka Camera feature is not working unfortunately. Yes, I do speak Russian. You can contact me in VK or telegram - @enty8080

**Closed** 2024-05-26 01:37 UTC
Labels: bug, help wanted
